/*

	events.js

	This file contains definitions of different events.
	Both client and server will read this file.

*/

SERVER = {
	STATUS : "SERVER_STATUS",
	USER_CONNECTED : "SERVER_USER_CONNECTED",
	USER_DISCONNECTED : "SERVER_USER_DISCONNECTED"
};

CHAT = {
	PUBLIC_MESSAGE : "CHAT_PUBLIC_MESSAGE",
	USER_LIST : "CHAT_USER_LIST"
};

GAME = {
	CREATE : "GAME_CREATE",
	DELETE : "GAME_DELETE",
	JOIN_REQUEST : "GAME_JOIN_REQUEST",
	START : "GAME_START",
	INFO : "GAME_INFO",
	STATUS : {
		PLAYING : "GAME_STATUS_PLAYING",
		// waiting for opponent
		WAITING : "GAME_STATUS_WAITING",
		IDLE : "GAME_STATUS_IDLE"
	},
	ACTION : {
		FIREAT : "GAME_ACTION_SHOOT",
		ADD_VERTICAL_SHIP : "GAME_ACTION_ADD_VERTICAL_SHIP",
		ADD_HORIZONTAL_SHIP : "GAME_ACTION_ADD_HORIZONTAL_SHIP",
		DELETE_SHIP : "GAME_ACTION_DELETE_SHIP",
		RESET_FIELD : "GAME_ACTION_RESET_FIELD",
		CONFIRM_ALIGNMENT : "GAME_ACTION_CONFIRM_ALIGNMENT",
		GET_ACTIVE_PLAYER_ID : "GAME_ACTION_GET_ACTIVE_PLAYER_ID",
		PRIVATE_CHAT : "GAME_ACTION_PRIVATE_CHAT"
	},
	PHASE : {
		ALIGNMENT : "GAME_PHASE_ALIGNMENT",
		BATTLE : "GAME_PHASE_BATTLE",
		GAME_OVER : "GAME_PHASE_GAME_OVER"
	}
};

CLIENT = {
	AUTH : "CLIENT_AUTH"
};

// for the server
if (typeof module != "undefined") {
	module.exports.SERVER = SERVER;
	module.exports.CHAT = CHAT;
	module.exports.GAME = GAME;
	module.exports.CLIENT = CLIENT;
}
